export const GET_ALL_COUNTRIES = "GET_ALL_COUNTRIES"; //OK

export const GET_COUNTRY_DETAIL = "GET_COUNTRY_DETAIL"; //OK

export const GET_COUNTRIES_BY_NAME = "GET_COUNTRIE_BY_NAME"; //OK

export const ORDER_A_TO_Z = "ORDER_A_TO_Z"; //OK

export const ORDER_Z_TO_A = "ORDER_Z_TO_A"; //NO HACE FALATA

export const FILTER_BY_CONTINENTS = "FILTER_BY_CONTINENTS"; //OK

export const CREATE_ACTIVITY = "CREATE_ACTIVITY";//OK   

export const GET_ALL_ACTIVITIES = "GET_ALL_ACTIVITIES"; //OK

export const FILTER_BY_ACTIVITY = "FILTER_BY_ACTIVITY"; //OK

export const CLEAR_STATE = "CLEAR_STATE"; //OK

